apiVersion: apps/v1
kind: Deployment
metadata:
  name: foursix-deployment
  labels:
    app: foursix-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foursix-deployment
  template:
    metadata:
      labels:
        app: foursix-deployment
    spec:
      containers:
      - name: c-foursix-deployment
        image: damffranco/four-six-api:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
