apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  #storageClassName: manual   --somente informar quando houver pv criado
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi