apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  namespace: mssql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce