apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqlserver
  name: foursixsql
spec:
  selector:
    app: mssql
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  type: LoadBalancer
