apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqlserver
  name: foursixordersql
spec:
  selector:
    app: mssql
  ports:
  - port: 1434
    protocol: TCP
    targetPort: 1433
  type: LoadBalancer
