apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-order-deployment
  labels:
    app: sqlserver-order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - containerPort: 1434
        env:
        - name: MSSQL_SA_PASSWORD
          value: 'SenhaDoBanco(123)'
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql/data
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-pvc